# Working with Text Data in scikit-learn

## Agenda

1. Model building in scikit-learn (refresher)
2. Representing text as numerical data
3. Reading the SMS data
4. Vectorizing the SMS data
5. Building a Naive Bayes model
6. Comparing Naive Bayes with logistic regression
7. Calculating the "spamminess" of each token
8. Creating a DataFrame from individual text files

In [1]:
# use print only as a function
from __future__ import print_function

## Part 1: Model building in scikit-learn (refresher)

In [ ]:
__author__ = 'swe03'

import numpy as np
import pandas as pd

desired_width = 250
pd.set_option('display.width',desired_width)

In [107]:
# Read in the csv file created in SQL Assistant, downloaded locally, and saved to C:\NLP_Files
#co_notes = pd.read_csv("C:\\NLP_Files\\cancelled_ord_notes.csv")
#co_notes.head(2)
type(co_notes)

#done_notes = pd.read_csv("C:\\NLP_Files\\done_ord_notes.csv")
#done_notes



pandas.core.frame.DataFrame

In [117]:
# Add the Target column and value
#co_notes['order'] = 0
#co_notes.head(1)
#type(co_notes["order"])  # This is a Series 
#print(co_notes["order"].dtype) # This is an int56
#type(co_notes["CUST_ORD_NBR"])  # This is a Series
#done_notes['order'] = 1
#done_notes

In [140]:
# I would rather use SQL for the data manipulation so.... installed the pandasql package via the Conda CLI interface 
# (i.e., Anaconda Prompt) 

#from pandasql import PandaSQL 
#pdsql = PandaSQL()
#pdsql("""SELECT d.cust_ord_nbr, d.svc_line_nbr, d.crt_dt, d.stat_eff_ts, d.svc_typ_cd, d.svc_stat_cd, d.user_aud_id, d."order" from done_notes d """,locals())
#all_notes = pdsql("""SELECT d.cust_ord_nbr, d.svc_line_nbr, d.crt_dt, d.stat_eff_ts, d.svc_typ_cd, d.svc_stat_cd, d.user_aud_id, d."order",
#                   c."order" From done_notes d Join co_notes c On  d.cust_ord_nbr = c.cust_ord_nbr and d.str_loc_id   = d.str_loc_id""", locals())

#all_notes = pd.concat([done_notes, co_notes])
#all_notes["CUST_LOC"] = all_notes.CUST_ORD_NBR.astype(str).str.cat(all_notes.STR_LOC_ID.astype(str), sep='_')
#all_notes
#all_notes_i = all_notes.set_index(['CUST_ORD_NBR','STR_LOC_ID'])  ## Hierarchical Index
all_notes_i = all_notes.set_index(['CUST_LOC'])                   ## Single Index with combined Columns(created above)
#idx = all_notes_i.index
all_notes_i

#type(pdsql)
#pdsql("SELECT * from done_notes limit 5;",locals())
#local = locals()

ACTV_FLG ASSG_ASSOC_USER_ID      CLS_DT CLS_USER_AUD_ID CRT_SRC_MOD_ID CRT_USER_AUD_ID CUST_ORD_NBR  FLLW_UP_DT LAST_UPD_SNSH_ID             LAST_UPD_TS  ...            SRC_LAST_UPD_TS STR_LOC_ID SVC_LINE_NBR  SVC_NOTE_NBR  \
CUST_LOC                                                                                                                                                              ...                                                                    
643,037_258        Y                  ?           ?               ?              ?         MRT1803      643,037           ?        4,258,089  1/16/2016 18:27:16.595  ...     1/16/2016 14:57:24.905        258            1             1   
643,037_258        Y                  ?           ?               ?              ?          ERS015      643,037           ?        4,275,111  1/21/2016 18:21:16.529  ...     1/21/2016 11:15:35.507        258            1             2   
643,037_258        Y                  ?           ?               ?              ?          ERS015      643,037           ?        4,275,111  1/21/2016 18:21:16.498  ...     1/21/2016 11:30:39.932        258            2             1   
643,037_258        Y                  ?           ?               ?              ?          ERS015      643,037           ?        4,302,184  1/29/2016 18:23:40.695  ...     1/29/2016 11:52:20.274        258            1             3   
643,037_258        Y             ERS015    2/9/2016          ERS015              ?          RRQ084      643,037    2/1/2016        4,339,445   2/9/2016 18:23:55.625  ...      2/9/2016 13:02:29.510        258            1             4   
643,037_258        Y             RRQ084    2/2/2016          RRQ084              ?          ERS015      643,037    2/3/2016        4,315,800   2/2/2016 18:27:07.354  ...      2/2/2016 08:44:49.802        258            1             5   
643,037_258        Y                  ?           ?               ?              ?            VNDR      643,037           ?        4,312,350   2/1/2016 18:24:26.853  ...      2/1/2016 09:33:35.332        258            1             6   
643,037_258        Y                  ?           ?               ?              ?         TAM5409      643,037           ?        4,325,852   2/5/2016 18:22:29.095  ...      2/5/2016 09:28:42.193        258            2             2   
631,853_258        Y                  ?           ?               ?              ?          ERS015      631,853           ?              NaN                     NaN  ...    11/12/2015 09:51:57.901        258            4             1   
631,853_258        Y                  ?           ?               ?              ?          ERS015      631,853           ?              NaN                     NaN  ...    11/12/2015 09:53:43.555        258            4             2   
631,853_258        Y                  ?  11/13/2015          ERS015              ?          INSTLR      631,853  11/13/2015              NaN                     NaN  ...    11/13/2015 16:44:07.342        258            2             1   
631,853_258        Y                  ?  11/13/2015          ERS015              ?          INSTLR      631,853  11/13/2015              NaN                     NaN  ...    11/13/2015 16:43:50.143        258            2             2   
631,853_258        Y                  ?  11/13/2015          ERS015              ?          INSTLR      631,853  11/13/2015              NaN                     NaN  ...    11/13/2015 16:43:25.473        258            4             3   
631,853_258        Y                  ?  11/13/2015          ERS015              ?          INSTLR      631,853  11/13/2015              NaN                     NaN  ...    11/13/2015 16:43:19.121        258            4             4   
631,853_258        Y             ERS015  11/16/2015          ERS015              ?          ERS015      631,853  11/16/2015              NaN                     NaN  ...    11/16/2015 18:03:14.882        

In [134]:
# store the feature matrix (X) and response vector (y).  The pdsql function automatically creates a DataFrame
X = pdsql("""SELECT svc_note_txt,cust_loc from all_notes""",locals())
y = pdsql("""SELECT "order" from all_notes""",locals())

In [135]:
# check the shapes of X and y
print(type(X))
print(type(y))
print(X.shape)
print(y.shape)
#print(y)
print(X)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(34, 2)
(34, 1)
                                         SVC_NOTE_TXT     CUST_LOC
0   Customer came in to check on the ETA of the order  643,037_258
1                                     01/21 eta 01/27  643,037_258
2   01/21 Clyde will be calling the store on 01/27...  643,037_258
3                                     01/29 eta 02/03  643,037_258
4   customer call inquired about cancelling wants ...  643,037_258
5        02/1 So Mr. Mize doesn't want the door. Ella  643,037_258
6   ** FROM VNDR ATTN: PRODUCT SHIPPED ON 02/01/20...  643,037_258
7   1st Call to Schedule - 7 days- called customer...  643,037_258
8   11/12 Chassidy will be coming into the store t...  631,853_258
9   11/12 I talk to Jeremy/Overhead to let him kno...  631,853_258
10  **FROM D30 SVC PROV:11/13/15 INS/Joanne called...  631,853_258
11  **FROM D30 SVC PROV:11/13/15 Calling HD to req...  631,853_258
12  **FROM D30 SVC PROV:11/13/15 INS/

In [163]:
all_notes_2 = pdsql("""SELECT cust_loc,"order",svc_note_txt from all_notes""",locals())
#all_notes_2.head(10)
all_notes_f = all_notes_2.groupby(['CUST_LOC']).first()
all_notes_f['first_flg'] = 1
#Flag_FRecs.reset_index(inplace=True)
##Flag_FRecs.ix[:2,['post_visid','date_time','first_flg','last_flg']]

all_notes_l = all_notes_2.groupby(['CUST_LOC']).last()
all_notes_l['last_flg'] = 1
#Flag_LRecs.reset_index(inplace=True)
##Flag_LRecs.ix[:2,['post_visid','date_time','first_flg','last_flg']]

print(all_notes_f)
print(all_notes_l)
all_notes_2

dataframes = [all_notes_f, all_notes_l]  # This is a List to just create the dataframes object (unecessary but illustrative)
flag_all = pd.concat(dataframes)  # This is a dataframe
flag_all

             order                                       SVC_NOTE_TXT  first_flg
CUST_LOC                                                                        
631,853_258      0  11/12 Chassidy will be coming into the store t...          1
643,037_258      1  Customer came in to check on the ETA of the order          1
             order                                       SVC_NOTE_TXT  last_flg
CUST_LOC                                                                       
631,853_258      0  Customer Not Ready - 7 days- no action taken w...         1
643,037_258      1  1st Call to Schedule - 7 days- called customer...         1


SVC_NOTE_TXT  first_flg  last_flg  order
CUST_LOC                                                                                  
631,853_258  11/12 Chassidy will be coming into the store t...        1.0       NaN      0
643,037_258  Customer came in to check on the ETA of the order        1.0       NaN      1
631,853_258  Customer Not Ready - 7 days- no action taken w...        NaN       1.0      0
643,037_258  1st Call to Schedule - 7 days- called customer...        NaN       1.0      1

In [167]:
Final_Recs = pdsql("""Select a.*, b.first_flg, b.last_flg   
       From all_notes_2 a   
       left outer join flag_all b
       On  a.cust_loc = b.cust_loc
       and a.svc_note_txt = b.svc_note_txt""", locals())
       
Final_Recs

CUST_LOC  order                                       SVC_NOTE_TXT  first_flg  last_flg
0   643,037_258      1  Customer came in to check on the ETA of the order        1.0       NaN
1   643,037_258      1                                    01/21 eta 01/27        NaN       NaN
2   643,037_258      1  01/21 Clyde will be calling the store on 01/27...        NaN       NaN
3   643,037_258      1                                    01/29 eta 02/03        NaN       NaN
4   643,037_258      1  customer call inquired about cancelling wants ...        NaN       NaN
5   643,037_258      1       02/1 So Mr. Mize doesn't want the door. Ella        NaN       NaN
6   643,037_258      1  ** FROM VNDR ATTN: PRODUCT SHIPPED ON 02/01/20...        NaN       NaN
7   643,037_258      1  1st Call to Schedule - 7 days- called customer...        NaN       1.0
8   631,853_258      0  11/12 Chassidy will be coming into the store t...        1.0       NaN
9   631,853_258      0  11/12 I talk to Jeremy/Overhead to let him kno...        NaN       NaN
10  631,853_258      0  **FROM D30 SVC PROV:11/13/15 INS/Joanne called...        NaN       NaN
11  631,853_258      0  **FROM D30 SVC PROV:11/13/15 Calling HD to req...        NaN       NaN
12  631,853_258      0  **FROM D30 SVC PROV:11/13/15 INS/Joanne called...        NaN       NaN
13  631,853_258      0  **FROM D30 SVC PROV:11/13/15 Calling HD to req...        NaN       NaN
14  631,853_258      0  11/13 Call Jeremy to see if they talk to the i...        NaN       NaN
15  631,853_258      0  **FROM D30 SVC PROV:..cont  also be an extra c...        NaN       NaN
16  631,853_258      0  **FROM D30 SVC PROV:11/16/2015 Spoke to Ins an...        NaN       NaN
17  631,853_258      0  11/16 I informed Chassidy that add'l cost per ...        NaN       NaN
18  631,853_258      0     Other - 10 days- 11/20 waiting on the customer        NaN       NaN
19  631,853_258      0  12/08 Jeff: Customer request that her install ...        NaN       NaN
20  631,853_258      0       12/08 Jeff:  Customer cancelled. Thanks Ella        NaN       NaN
21  631,853_258      0  Ella-Ms Avery LVM on Wednesday afternoon askin...        NaN       NaN
22  631,853_258      0                                  ***Avery-see Ella        NaN       NaN
23  631,853_258      0  12/28 Jeremy said that the install manager wil...        NaN       NaN
24  631,853_258      0  **FROM D30 SVC PROV:Can you please call us at ...        NaN       NaN
25  631,853_258      0  01/14Chassidy is having a problem finding somo...        NaN       NaN
26  631,853_258      0  01/14 I told her that I will call Jeff/Clopay ...        NaN       NaN
27  631,853_258      0  Status: Awaiting Special Order - 7 days- 01/15...        NaN       NaN
28  631,853_258      0  Checking Status: Left Message - 2 days- 02/03 ...        NaN       NaN
29  631,853_258      0  Status: Customer not ready - 7 days- 02/10 Cha...        NaN       NaN
30  631,853_258      0  2/17 Customer will be coming in to return the ...        NaN       NaN
31  631,853_258      0  02/17 I had to add a busted trip charge for th...        NaN       NaN
32  631,853_258      0  **FROM D30 SVC PROV:2/17/16 Related to PO#2149...        NaN       NaN
33  631,853_258      0  Customer Not Ready - 7 days- no action taken w...        NaN       1.0

In [153]:
#print(type(all_notes_2))
#print(all_notes_2)
#all_notes_t = all_notes_2.T
#all_notes_t
#all_notes_t["all_txt"] = [' '.join(row) for row in all_notes_t[all_notes_t.columns[:]].values]   ## Did not work
#all_notes_t

In [177]:
temp_list = []
temp_dict = {'CUST_LOC': row['CUST_LOC'], 'order': row['order'],   }
                     

# Loop through the records to create the ADS
n = 0
for index, row in Final_Recs.iterrows():  # if you don't include index then "TypeError: tuple indices must be integers or slices, not str"
    #print('top o the for statement')
    #print('evar4 =', (row['evar4 ']))
    #print ('first_flg=', CR_merge['first_flg_y'][n])
    
    if row['first_flg'] == 1 :  # This is to start the build of the Cust_Loc single notes variable
        temp_list = []
        temp_list.append(row['SVC_NOTE_TXT'])
    elif row['last_flg'] == 1:
        temp_list.append(row['SVC_NOTE_TXT'])
        ##temp_list = []
    else:
        temp_list.append(row['SVC_NOTE_TXT'])
        
    
    ##    temp_list.append(temp_dict)

## out = pd.DataFrame(temp_list)

In [178]:
temp_list

['11/12 Chassidy will be coming into the store to pay the bal. due on the 2nd install that was left off the order in error. Ella',
 '11/12 I talk to Jeremy/Overhead to let him know that the 2nd po was added for the 2nd GDO. He will inform the installer.',
 '**FROM D30 SVC PROV:11/13/15 INS/Joanne called (she and tech both spoke with JM yesterday) Need trip charge for the dead run. First cust had2nd Po created since she had 2 gdos but beam prevented install(JS) : XML,SYSTEM',
 '**FROM D30 SVC PROV:11/13/15 Calling HD to request trip charge - the two POs are21491465 and 21491503. I have beenon hold for 13 minutes andno one at HD answered -sending emaill to COS (JS) : XML,SYSTEM',
 '**FROM D30 SVC PROV:11/13/15 INS/Joanne called (she and tech both spoke with JM yesterday) Need trip charge for the dead run. First cust had2nd PO created since she had 2 gdos but beam prevented install(JS) : XML,SYSTEM',
 '**FROM D30 SVC PROV:11/13/15 Calling HD to request trip charge - the two POs are2149146

In order to **build a model**, the features must be **numeric**, and every observation must have the **same features in the same order**.

In order to make a **prediction**, the new observation must have the **same features as the training observations**, both in number and meaning.

## Part 2: Representing text as numerical data

In [8]:
# example text for model training (SMS messages)
simple_train = ['call you tonight', 'Call me a cab', 'please call me... PLEASE!']

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> Text Analysis is a major application field for machine learning algorithms. However the raw data, a sequence of symbols cannot be fed directly to the algorithms themselves as most of them expect **numerical feature vectors with a fixed size** rather than the **raw text documents with variable length**.

We will use [CountVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) to "convert text into a matrix of token counts":

In [9]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [10]:
# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(simple_train)

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [11]:
# examine the fitted vocabulary
vect.get_feature_names()

[u'cab', u'call', u'me', u'please', u'tonight', u'you']

In [12]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm

<3x6 sparse matrix of type '<type 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [13]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]], dtype=int64)

In [14]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> In this scheme, features and samples are defined as follows:

> - Each individual token occurrence frequency (normalized or not) is treated as a **feature**.
> - The vector of all the token frequencies for a given document is considered a multivariate **sample**.

> A **corpus of documents** can thus be represented by a matrix with **one row per document** and **one column per token** (e.g. word) occurring in the corpus.

> We call **vectorization** the general process of turning a collection of text documents into numerical feature vectors. This specific strategy (tokenization, counting and normalization) is called the **Bag of Words** or "Bag of n-grams" representation. Documents are described by word occurrences while completely ignoring the relative position information of the words in the document.

In [15]:
# print the sparse matrix
print(simple_train_dtm)

  (0, 1)	1
  (0, 4)	1
  (0, 5)	1
  (1, 0)	1
  (1, 1)	1
  (1, 2)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	2


From the [scikit-learn documentation](http://scikit-learn.org/stable/modules/feature_extraction.html#text-feature-extraction):

> As most documents will typically use a very small subset of the words used in the corpus, the resulting matrix will have **many feature values that are zeros** (typically more than 99% of them).

> For instance, a collection of 10,000 short text documents (such as emails) will use a vocabulary with a size in the order of 100,000 unique words in total while each document will use 100 to 1000 unique words individually.

> In order to be able to **store such a matrix in memory** but also to **speed up operations**, implementations will typically use a **sparse representation** such as the implementations available in the `scipy.sparse` package.

In [16]:
# example text for model testing
simple_test = ["please don't call me"]

In order to make a **prediction**, the new observation must have the **same features as the training observations**, both in number and meaning.

In [17]:
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 1, 1, 1, 0, 0]], dtype=int64)

In [18]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0

**Summary:**

- `vect.fit(train)` **learns the vocabulary** of the training data
- `vect.transform(train)` uses the **fitted vocabulary** to build a document-term matrix from the training data
- `vect.transform(test)` uses the **fitted vocabulary** to build a document-term matrix from the testing data (and **ignores tokens** it hasn't seen before)

## Part 3: Reading the SMS data

In [19]:
# read file into Pandas from a URL
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/sms.tsv'
sms = pd.read_table(url, header=None, names=['label', 'message'])

In [20]:
# alternative: read file into Pandas using a relative path
path = '../data/sms.tsv'
sms = pd.read_table(path, header=None, names=['label', 'message'])

In [21]:
# examine the shape
sms.shape

(5572, 2)

In [22]:
# examine the first 10 rows
sms.head(10)

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [23]:
# examine the class distribution
sms.label.value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [24]:
# convert label to a numerical variable
sms['label_num'] = sms.label.map({'ham':0, 'spam':1})

In [25]:
# check that the conversion worked
sms.head(10)

label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0
5  spam  FreeMsg Hey there darling it's been 3 week's n...          1
6   ham  Even my brother is not like to speak with me. ...          0
7   ham  As per your request 'Melle Melle (Oru Minnamin...          0
8  spam  WINNER!! As a valued network customer you have...          1
9  spam  Had your mobile 11 months or more? U R entitle...          1

In [26]:
# usual way to define X and y (from the iris data) for use with a MODEL
X = iris.data
y = iris.target
print(X.shape)
print(y.shape)

(150L, 4L)
(150L,)


In [27]:
# required way to define X and y for use with COUNTVECTORIZER
X = sms.message
y = sms.label_num
print(X.shape)
print(y.shape)

(5572L,)
(5572L,)


In [28]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print(X_train.shape)
print(X_test.shape)

(4179L,)
(1393L,)


## Part 4: Vectorizing the SMS data

In [29]:
# instantiate the vectorizer
vect = CountVectorizer()

In [30]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [31]:
# alternative: combine fit and transform into a single step
X_train_dtm = vect.fit_transform(X_train)

In [32]:
# examine the document-term matrix
X_train_dtm

<4179x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 55209 stored elements in Compressed Sparse Row format>

In [33]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1393x7456 sparse matrix of type '<type 'numpy.int64'>'
	with 17604 stored elements in Compressed Sparse Row format>

## Part 5: Building a Naive Bayes model

We will use [Multinomial Naive Bayes](http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html):

> The multinomial Naive Bayes classifier is suitable for classification with **discrete features** (e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

In [34]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [35]:
# train the model using X_train_dtm (timing it with an IPython "magic command")
%time nb.fit(X_train_dtm, y_train)

Wall time: 4 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [36]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [37]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.98851399856424982

In [38]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[1203,    5],
       [  11,  174]])

In [39]:
# print message text for the false positives (meaning they were incorrectly classified as spam)
X_test[y_test < y_pred_class]

574               Waiting for your call.
3375             Also andros ice etc etc
45      No calls..messages..missed calls
3415             No pic. Please re-send.
1988    No calls..messages..missed calls
Name: message, dtype: object

In [40]:
# print message text for the false negatives (meaning they were incorrectly classified as ham)
X_test[y_test > y_pred_class]

3132    LookAtMe!: Thanks for your purchase of a video...
5       FreeMsg Hey there darling it's been 3 week's n...
3530    Xmas & New Years Eve tickets are now on sale f...
684     Hi I'm sue. I am 20 years old and work as a la...
1875    Would you like to see my XXX pics they are so ...
1893    CALL 09090900040 & LISTEN TO EXTREME DIRTY LIV...
4298    thesmszone.com lets you send free anonymous an...
4949    Hi this is Amy, we will be sending you a free ...
2821    INTERFLORA - “It's not too late to order Inter...
2247    Hi ya babe x u 4goten bout me?' scammers getti...
4514    Money i have won wining number 946 wot do i do...
Name: message, dtype: object

In [41]:
# what do you notice about the false negatives?
X_test[3132]

"LookAtMe!: Thanks for your purchase of a video clip from LookAtMe!, you've been charged 35p. Think you can do better? Why not send a video in a MMSto 32323."

In [42]:
# calculate predicted probabilities for X_test_dtm (poorly calibrated)
y_pred_prob = nb.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([  2.87744864e-03,   1.83488846e-05,   2.07301295e-03, ...,
         1.09026171e-06,   1.00000000e+00,   3.98279868e-09])

In [43]:
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.98664310005369604

## Part 6: Comparing Naive Bayes with logistic regression

In [44]:
# import and instantiate a logistic regression model
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [45]:
# train the model using X_train_dtm
%time logreg.fit(X_train_dtm, y_train)

Wall time: 50 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [46]:
# make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test_dtm)

In [47]:
# calculate predicted probabilities for X_test_dtm (well calibrated)
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([ 0.01269556,  0.00347183,  0.00616517, ...,  0.03354907,
        0.99725053,  0.00157706])

In [48]:
# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

0.9877961234745154

In [49]:
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.99368176123143015

## Part 7: Calculating the "spamminess" of each token

In [50]:
# store the vocabulary of X_train
X_train_tokens = vect.get_feature_names()
len(X_train_tokens)

7456

In [51]:
# examine the first 50 tokens
print(X_train_tokens[0:50])

[u'00', u'000', u'008704050406', u'0121', u'01223585236', u'01223585334', u'0125698789', u'02', u'0207', u'02072069400', u'02073162414', u'02085076972', u'021', u'03', u'04', u'0430', u'05', u'050703', u'0578', u'06', u'07', u'07008009200', u'07090201529', u'07090298926', u'07123456789', u'07732584351', u'07734396839', u'07742676969', u'0776xxxxxxx', u'07781482378', u'07786200117', u'078', u'07801543489', u'07808', u'07808247860', u'07808726822', u'07815296484', u'07821230901', u'07880867867', u'0789xxxxxxx', u'07946746291', u'0796xxxxxx', u'07973788240', u'07xxxxxxxxx', u'08', u'0800', u'08000407165', u'08000776320', u'08000839402', u'08000930705']


In [52]:
# examine the last 50 tokens
print(X_train_tokens[-50:])

[u'yer', u'yes', u'yest', u'yesterday', u'yet', u'yetunde', u'yijue', u'ym', u'ymca', u'yo', u'yoga', u'yogasana', u'yor', u'yorge', u'you', u'youdoing', u'youi', u'youphone', u'your', u'youre', u'yourjob', u'yours', u'yourself', u'youwanna', u'yowifes', u'yoyyooo', u'yr', u'yrs', u'ything', u'yummmm', u'yummy', u'yun', u'yunny', u'yuo', u'yuou', u'yup', u'zac', u'zaher', u'zealand', u'zebra', u'zed', u'zeros', u'zhong', u'zindgi', u'zoe', u'zoom', u'zouk', u'zyada', u'\xe8n', u'\u3028ud']


In [53]:
# Naive Bayes counts the number of times each token appears in each class
nb.feature_count_

array([[  0.,   0.,   0., ...,   1.,   1.,   1.],
       [  5.,  23.,   2., ...,   0.,   0.,   0.]])

In [54]:
# rows represent classes, columns represent tokens
nb.feature_count_.shape

(2L, 7456L)

In [55]:
# number of times each token appears across all HAM messages
ham_token_count = nb.feature_count_[0, :]
ham_token_count

array([ 0.,  0.,  0., ...,  1.,  1.,  1.])

In [56]:
# number of times each token appears across all SPAM messages
spam_token_count = nb.feature_count_[1, :]
spam_token_count

array([  5.,  23.,   2., ...,   0.,   0.,   0.])

In [57]:
# create a DataFrame of tokens with their separate ham and spam counts
tokens = pd.DataFrame({'token':X_train_tokens, 'ham':ham_token_count, 'spam':spam_token_count}).set_index('token')

In [58]:
# examine 5 random DataFrame rows
tokens.sample(5, random_state=6)

ham  spam
token                  
very           64     2
nasty           1     1
villa           0     1
beloved         1     0
textoperator    0     2

Before we can use this to calculate the **"spamminess" of each token**, we need to avoid **dividing by zero** and account for the **class imbalance**.

In [59]:
# add 1 to ham and spam counts to avoid dividing by 0
tokens['ham'] = tokens.ham + 1
tokens['spam'] = tokens.spam + 1
tokens.sample(5, random_state=6)

ham  spam
token                  
very           65     3
nasty           2     2
villa           1     2
beloved         2     1
textoperator    1     3

In [60]:
# Naive Bayes counts the number of observations in each class
nb.class_count_

array([ 3617.,   562.])

In [61]:
# convert the ham and spam counts into frequencies
tokens['ham'] = tokens.ham / nb.class_count_[0]
tokens['spam'] = tokens.spam / nb.class_count_[1]
tokens.sample(5, random_state=6)

ham      spam
token                           
very          0.017971  0.005338
nasty         0.000553  0.003559
villa         0.000276  0.003559
beloved       0.000553  0.001779
textoperator  0.000276  0.005338

In [62]:
# calculate the ratio of spam-to-ham for each token
tokens['spam_ratio'] = tokens.spam / tokens.ham
tokens.sample(5, random_state=6)

ham      spam  spam_ratio
token                                       
very          0.017971  0.005338    0.297044
nasty         0.000553  0.003559    6.435943
villa         0.000276  0.003559   12.871886
beloved       0.000553  0.001779    3.217972
textoperator  0.000276  0.005338   19.307829

In [63]:
# examine the DataFrame sorted by spam_ratio
# note: use sort() instead of sort_values() for pandas 0.16.2 and earlier
tokens.sort_values('spam_ratio', ascending=False)

ham      spam  spam_ratio
token                                     
claim       0.000276  0.158363  572.798932
prize       0.000276  0.135231  489.131673
150p        0.000276  0.087189  315.361210
tone        0.000276  0.085409  308.925267
guaranteed  0.000276  0.076512  276.745552
18          0.000276  0.069395  251.001779
cs          0.000276  0.065836  238.129893
www         0.000553  0.129893  234.911922
1000        0.000276  0.056940  205.950178
awarded     0.000276  0.053381  193.078292
150ppm      0.000276  0.051601  186.642349
uk          0.000553  0.099644  180.206406
500         0.000276  0.048043  173.770463
ringtone    0.000276  0.044484  160.898577
000         0.000276  0.042705  154.462633
mob         0.000276  0.042705  154.462633
co          0.000553  0.078292  141.590747
collection  0.000276  0.039146  141.590747
valid       0.000276  0.037367  135.154804
2000        0.000276  0.037367  135.154804
800         0.000276  0.037367  135.154804
10p         0.000276  0.037367  135.154804
8007        0.000276  0.035587  128.718861
16          0.000553  0.067616  122.282918
weekly      0.000276  0.033808  122.282918
tones       0.000276  0.032028  115.846975
land        0.000276  0.032028  115.846975
http        0.000276  0.032028  115.846975
national    0.000276  0.030249  109.411032
5000        0.000276  0.030249  109.411032
...              ...       ...         ...
went        0.012718  0.001779    0.139912
ll          0.052530  0.007117    0.135494
told        0.013824  0.001779    0.128719
feel        0.013824  0.001779    0.128719
gud         0.014100  0.001779    0.126195
cos         0.014929  0.001779    0.119184
but         0.090683  0.010676    0.117731
amp         0.015206  0.001779    0.117017
something   0.015206  0.001779    0.117017
sure        0.015206  0.001779    0.117017
ok          0.061100  0.007117    0.116488
said        0.016312  0.001779    0.109084
morning     0.016865  0.001779    0.105507
yeah        0.017694  0.001779    0.100562
lol         0.017694  0.001779    0.100562
anything    0.017971  0.001779    0.099015
my          0.150401  0.014235    0.094646
doing       0.019077  0.001779    0.093275
way         0.019630  0.001779    0.090647
ask         0.019630  0.001779    0.090647
already     0.019630  0.001779    0.090647
too         0.021841  0.001779    0.081468
come        0.048936  0.003559    0.072723
later       0.030688  0.001779    0.057981
lor         0.032900  0.001779    0.054084
da          0.032900  0.001779    0.054084
she         0.035665  0.001779    0.049891
he          0.047000  0.001779    0.037858
lt          0.064142  0.001779    0.027741
gt          0.064971  0.001779    0.027387

[7456 rows x 3 columns]

In [64]:
# look up the spam_ratio for a given token
tokens.loc['dating', 'spam_ratio']

83.667259786476862

## Part 8: Creating a DataFrame from individual text files

In [65]:
# use glob to create a list of ham filenames
import glob
ham_filenames = glob.glob('../data/ham_files/*.txt')
ham_filenames

['../data/ham_files\\email1.txt',
 '../data/ham_files\\email3.txt',
 '../data/ham_files\\email5.txt']

In [66]:
# read the contents of the ham files into a list (each list element is one email)
ham_text = []
for filename in ham_filenames:
    with open(filename) as f:
        ham_text.append(f.read())
ham_text

['This is a ham email.\nIt has 2 lines.\n',
 'This is another ham email.\n',
 'This is yet another ham email.\n']

In [67]:
# repeat this process for the spam files
spam_filenames = glob.glob('../data/spam_files/*.txt')
spam_text = []
for filename in spam_filenames:
    with open(filename) as f:
        spam_text.append(f.read())
spam_text

['This is a spam email.\n', 'This is another spam email.\n']

In [68]:
# combine the ham and spam lists
all_text = ham_text + spam_text
all_text

['This is a ham email.\nIt has 2 lines.\n',
 'This is another ham email.\n',
 'This is yet another ham email.\n',
 'This is a spam email.\n',
 'This is another spam email.\n']

In [69]:
# create a list of labels (ham=0, spam=1)
all_labels = [0]*len(ham_text) + [1]*len(spam_text)
all_labels

[0, 0, 0, 1, 1]

In [70]:
# convert the lists into a DataFrame
pd.DataFrame({'label':all_labels, 'message':all_text})

label                                  message
0      0  This is a ham email.\nIt has 2 lines.\n
1      0             This is another ham email.\n
2      0         This is yet another ham email.\n
3      1                  This is a spam email.\n
4      1            This is another spam email.\n